##
# Label incoming pull requests according to configuration in .github/labeler.yml
##
name: Pull Request Labeler
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    # See documentation: https://github.com/actions/labeler
    - uses: actions/labeler@v5
